Code review 4
effgenij/js-basics pull request #4
Opened 2024-07-07 13:59 UTC by effgenij

Code review 4

2024-07-09 19:45 UTC, Levitinn requested changes

2024-07-09 19:45 UTC, Levitinn commented on 15-task-object/toDoList.js
> +    addTask(title, priority) {
```
addTask(title, priority) {
      this.tasks.push({ id, title, priority });
      this.lastID = this.lastID + 1;
}
```

2024-07-09 19:45 UTC, Levitinn commented on 15-task-object/toDoList.js
> +      }else {
потерял пробел перед else

2024-07-09 19:45 UTC, Levitinn commented on 15-task-object/toDoList.js
> +  };
```
sortTasks(sortBy, order = 'asc') {
      if (sortBy !== 'id' || sortBy !== 'priority') {
            console.log('......');
            return;
      }
      this.tasks.sort((a, b) => (order === 'asc' ? a.[sortBy] - b.[sortBy] : b.[sortBy] - a.[sortBy]));
    },
```

2024-07-09 20:08 UTC, effgenij commented on 15-task-object/toDoList.js
> +    addTask(title, priority) {
Тогда наверно надо lastID начинать с 1,а не как у меня с 0? Ведь тогда получится что первый id будет нулевым.

2024-07-23 06:37 UTC, Levitinn requested changes

2024-07-23 06:37 UTC, Levitinn commented on 15-task-object/toDoList.js
> +    addTask(title, priority) {
как хочешь. я лишь показал,  как можно сократить тот кто, что написал ты в методе

2024-07-23 11:18 UTC, merged